package auth

import (
	"errors"
	"github.com/golang-jwt/jwt/v5"
	"time"
)

type JWTService struct {
	secretKey []byte
	expires   time.Duration
}

func NewJWTService(secretKey string, expires time.Duration) *JWTService {
	return &JWTService{
		secretKey: []byte(secretKey),
		expires:   expires,
	}
}

func (s *JWTService) GenerateToken(userID string) (string, error) {
	claims := jwt.MapClaims{
		"user_id": userID,
		"guest":   false,
		"exp":     time.Now().Add(s.expires).Unix(),
		"iat":     time.Now().Unix(),
	}

	token := jwt.NewWithClaims(jwt.SigningMethodHS256, claims)

	return token.SignedString(s.secretKey)
}

func (s *JWTService) GenerateGuestToken(guestID string) (string, error) {
	claims := jwt.MapClaims{
		"user_id": guestID,
		"guest":   true,
		// Allow 30 minute sessions for guests
		"exp": time.Now().Add(30 * time.Minute).Unix(),
		"iat": time.Now().Unix(),
	}

	token := jwt.NewWithClaims(jwt.SigningMethodHS256, claims)

	return token.SignedString(s.secretKey)
}

// Validates token, checks if token is generated by guest session
func (s *JWTService) ValidateToken(tokenString string) (string, bool, error) {
	token, err := jwt.Parse(tokenString, func(token *jwt.Token) (interface{}, error) {
		if _, ok := token.Method.(*jwt.SigningMethodHMAC); !ok {
			return nil, errors.New("unexpected signing method")
		}
		return s.secretKey, nil
	})

	if err != nil {
		return "", false, err
	}

	if claims, ok := token.Claims.(jwt.MapClaims); ok && token.Valid {
		userID, ok := claims["user_id"].(string)
		if !ok {
			return "", false, errors.New("user_id missing in token")
		}

		guest, ok := claims["guest"].(bool)
		if !ok {
			guest = false
		}
		return userID, guest, nil
	}

	return "", false, errors.New("invalid token")
}
